// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVBSe5K3VIc1lk4dN0mLztJa-b0_jDXf4',
    appId: '1:830601114588:web:8a0ea304ce1cf1f2825519',
    messagingSenderId: '830601114588',
    projectId: 'car-parking-dhruv',
    authDomain: 'car-parking-dhruv.firebaseapp.com',
    databaseURL: 'https://car-parking-dhruv-default-rtdb.firebaseio.com',
    storageBucket: 'car-parking-dhruv.appspot.com',
    measurementId: 'G-QXDZQXB9YS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMNxSNYDjTKsKXnsF51Rl-Ljr_7DNhmIg',
    appId: '1:830601114588:android:6c71811d86becefe825519',
    messagingSenderId: '830601114588',
    projectId: 'car-parking-dhruv',
    databaseURL: 'https://car-parking-dhruv-default-rtdb.firebaseio.com',
    storageBucket: 'car-parking-dhruv.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdPGIOJg1VMt9vKBsJMs2vXck3nvKJaM8',
    appId: '1:830601114588:ios:d56406502607680c825519',
    messagingSenderId: '830601114588',
    projectId: 'car-parking-dhruv',
    databaseURL: 'https://car-parking-dhruv-default-rtdb.firebaseio.com',
    storageBucket: 'car-parking-dhruv.appspot.com',
    iosClientId: '830601114588-01dut0pvqq8udj3mlghn8r42mpihu943.apps.googleusercontent.com',
    iosBundleId: 'com.dhrisdhruv.carParking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdPGIOJg1VMt9vKBsJMs2vXck3nvKJaM8',
    appId: '1:830601114588:ios:d56406502607680c825519',
    messagingSenderId: '830601114588',
    projectId: 'car-parking-dhruv',
    databaseURL: 'https://car-parking-dhruv-default-rtdb.firebaseio.com',
    storageBucket: 'car-parking-dhruv.appspot.com',
    iosClientId: '830601114588-01dut0pvqq8udj3mlghn8r42mpihu943.apps.googleusercontent.com',
    iosBundleId: 'com.dhrisdhruv.carParking',
  );
}
